### ISSUE TITLE
Unmutes audio if muted

### ISSUE THREAD

**Issue by swrobel** [jpwenzel/reset-audio-balance#2]
Any idea how to prevent it from doing so?

**Comment by jpwenzel** [comment]
The script actually a side effect of a volume reset to serve its purpose... The balance is reset when the volume is... the issue never occurred to me as I didn't mute the computer... good find!

Let's see if I can come up with a simple solution to check on the mute state before executing the reset (so the script can restore the mute state after it has performed the balance/volume reset).

**Comment by jpwenzel** [comment]
Fixed! :)

**Comment by swrobel** [comment]
Wow, amazing! thanks for the quick turnaround!!!
